services:
  - type: web
    name: cinema-ai-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
      - key: SKIP_AUTH
        value: "true"
